heat_template_version: 2013-05-23
# Author: Miguel Angel Diego Alfageme
# Date: 05/09/2017
# Purpose: Deploy VM resources a Docker host
# on Fujitsu's Cloud Service K5 IaaS Platform
#
#
description: Deploy Network & Ubuntu Image with Docker

# Input parameters
parameters:
  name_preffix:
    type: string
    label: Name preffix
    description: Name preffix used to concat to all the resources (unique for K5 project)
    default: "cnets-iccs"
  k5_ubuntu_image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: "Ubuntu Server 16.04 LTS (English) 01"
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: "C-1"
  key_pair:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: "cnets-mdiego"
  public_net:
    type: string
    label: public network id
    description: id of public network to supply floating ips
    default: "05e4ab97-297e-4470-821a-67505973e687"
  private_net:
    type: string
    label: private network id
    description: id of private network 
    default: "10.20.20.0/24"
  routerid:
    type: string
    label: Router ID
    description: Router to link public and private net
    default: "fa137d69-f35c-4160-b6e1-5927033eb465"
  az:
    type: string
    label: Availability Zone
    description: Region AZ to use
    default: "es-1a"

# K5 Infrastructure resources to be built
resources:

# Create docker & http access
  
  server_port:
    type: OS::Neutron::Port
    properties:
      availability_zone: { get_param: az }
      network: { get_param: private_network }
      security_groups:
        - { get_param: security_group }
        
  # -------------------------------------------------------------------------
  # Create a system volume for use with the server
  docker_sys_vol:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: az }
      name:
        str_replace:
          template: "$name_preffix-box"
          params:
            "$name_preffix": { get_param: name_preffix } 
      size: 20
      volume_type: "M1"
      image : { get_param: k5_ubuntu_image }

# Build a docker server using the system volume defined above
  docker_server:
    type: OS::Nova::Server
    depends_on: [ server_port, docker_sys_vol ]
    properties:
      availability_zone: { get_param: az }
      name:
        str_replace:
          template: "$name_preffix-server"
          params:
            "$name_preffix": { get_param: name_preffix } 
      key_name: { get_param: key_pair }
      flavor: { get_param: flavor }
      admin_user: ubuntu
      image : { get_param: k5_ubuntu_image }
      metadata: { "fcx.autofailover": True }
      block_device_mapping: [{"volume_size": "20", "volume_id": { get_resource: docker_sys_vol }, "delete_on_termination": True, "device_name": "/dev/vda"}]
      networks:
        - port: { get_resource: server_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            apt_update: true
            runcmd:
              # Config hostname resolution
              - echo $app_ip `hostname` >> /etc/hosts
              # Install Docker
              - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              - sudo apt-get update
              - apt-cache policy docker-ce
              - sudo apt-get install -y docker-ce
              - sleep 90
              - sudo usermod -aG docker ubuntu
              - sudo docker run -p 80:8082 -d madhosoi/k5websample
                          
          params:
            $app_ip: { get_attr: [server_port, fixed_ips, 0, ip_address]}
            message: "Installation of Docker Service Complete"
# Allocate a floating/global ip address
  docker_server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      availability_zone: { get_param: az }
      floating_network_id: { get_param: public_net }

# Assign a floating/global ip address to the fixed server ip address
  docker_server_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: [docker_server_floating_ip, server_port]
    properties:
      floatingip_id: { get_resource: docker_server_floating_ip }
      port_id: { get_resource: server_port }
# ----------------------------------------------------------------------------------